### ISSUE TITLE
Error when running awsmobile init

### ISSUE THREAD

**Issue by benholtz** [aws/awsmobile-cli#120]
#77 #81 
Same issue as referenced tickets above.

```
/Users/****/.nvm/versions/node/v6.9.1/lib/node_modules/awsmobile-cli/lib/init-steps/s2-choose-strategy.js:104
async function inquirerForValid(initInfo){
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/*****/.nvm/versions/node/v6.9.1/lib/node_modules/awsmobile-cli/lib/command-init.js:16:24)
    at Module._compile (module.js:570:32)
```

npm 6.0.0
node v6.9.1
awsmobile-cli 1.1.2

**Comment by UnleashedMind** [comment]
please use node version 7 and above. 
or 8.9.0 for lst node version.

**Comment by benholtz** [comment]
This is completely the issue. 

nvm default fail.

Cheers!
