### ISSUE TITLE
Configuring cloud-api fails

### ISSUE THREAD

**Issue by davidray** [aws/awsmobile-cli#137]
Following the todos tutorial, when I try to set up cloud-api I get this:
```todos$ awsmobile cloud-api configure

cloud-api feature specification error:
/usr/local/lib/node_modules/awsmobile-cli/lib/feature-operations/scripts/cloud-api-ops.js:355
        ...path,
        ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.specify (/usr/local/lib/node_modules/awsmobile-cli/lib/backend-operations/ops-cloud-api.js:40:35)```

I'm on 1.1.4

**Comment by davidray** [comment]
I just needed to update node to the latest.
