### ISSUE TITLE
AWSMobile Init/Pull not working?

### ISSUE THREAD

**Issue by fchau-arrdude** [aws/awsmobile-cli#152]
Hello there. I'm running to a weird issue with my project. When I try doing an awsmobile pull or init for my project, it does not work. This is the error message I am getting:

`awsmobile project's specifications logged at:
    awsmobilejs/#current-backend-info/mobile-hub-project.yml
⠧ downloading cloud-api lambda function codebases/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Response.lambdaClient.getFunction (/usr/local/lib/node_modules/awsmobile-cli/lib/backend-operations/ops-cloud-api.js:160:46)
    at Request.<anonymous> (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:26:10`

I'm unsure what could have caused it. Can anyone give me some pointers on how to debug this? Many thanks!

**Comment by fchau-arrdude** [comment]
I'm having issues exactly similar to this ticket: https://github.com/aws/awsmobile-cli/issues/144

**Comment by UnleashedMind** [comment]
We are investigating this issue. 
Please provider this information
open your project's awsmobilejs/#current-backend-info/backend-details.json file, look for `AWS::Lambda::Function`, see if there is an attribute named `configHandlerName`

**Comment by UnleashedMind** [comment]
Is it that for every `AWS::Lambda::Function` there's a `configHandlerName` attribute? 
Or if there's one `AWS::Lambda::Function` that's missing the `configHandlerName` attribute?
