### ISSUE TITLE
getGraphqlApi err

### ISSUE THREAD

**Issue by goatandsheep** [aws/awsmobile-cli#182]
After accidentally deleting a large part of my awsmobile folder, I'm stuck because I cannot reconnect my existing AppSync to my project.

```
retrieving appsync: get graphql api...getGraphqlApi err 
{ NotFoundException: GraphQL API <proper appsync api> not found.
    at Object.extractError (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'GraphQL API <proper appsync api> not found.',
  code: 'NotFoundException',
  time: 2018-08-22T18:55:55.404Z,
  requestId: 'xxx',
  statusCode: 404,
  retryable: false,
  retryDelay: 92.10220404873277 }
appsync retrieve failed
{ NotFoundException: GraphQL API <proper appsync api> not found.
    at Object.extractError (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/xxx/installs/nodejs/8.10.0/.npm/lib/node_modules/awsmobile-cli/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'GraphQL API <proper appsync api> not found.',
  code: 'NotFoundException',
  time: 2018-08-22T18:55:55.404Z,
  requestId: 'xxx',
  statusCode: 404,
  retryable: false,
  retryDelay: 92.10220404873277 }
```

**Comment by UnleashedMind** [comment]
If you still have access to you online appsync project, there might be a way to recover. Just follow these steps: 
- Remove folder `awsmobilejs/backend/appsync'
- Remove folder `awsmobilejs/#current-backend-info/appsync`
- Change the content of the file (create the file if non-existing) `awsmobilejs/.awsmobile/info/appsync-info.json` to
`{
    "apiId": "<your appsync project id>",
    "region": "<your appsync project region>"
}`
- Execute `awsmobile pull`

**Comment by goatandsheep** [comment]
I ultimately decided to move away from awsmobile and am just sticking with amplify alone
